# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e213ff3aa620fe7c451ff52ce9b26c41"
name = "rmx-yuceler"
application_url = "https://web-production-e05ff.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "remixapp-2.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_products,write_products,read_publications,write_publications,read_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://web-production-e05ff.up.railway.app/api/auth",
  "https://web-production-e05ff.up.railway.app/api/auth/callback",
  "https://web-production-e05ff.up.railway.app/auth/callback"
]

[app_proxy]
url = "https://web-production-e05ff.up.railway.app"
subpath = "proxy"
prefix = "apps"
